version: '3.8'

services:
  web:
    build: .
    container_name: counselbot-web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:14-alpine
    container_name: counselbot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=counselbot
      - POSTGRES_USER=counselbot
      - POSTGRES_PASSWORD=counselbot
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
