# Generated by Django 4.2.20 on 2025-03-27 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career_counseling', '0003_add_sample_career_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SKILLS', 'Skills Assessment'), ('INTERESTS', 'Interest Assessment'), ('PERSONALITY', 'Personality Assessment'), ('SITUATION', 'Situational Assessment')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'question')},
        ),
        migrations.DeleteModel(
            name='AssessmentResult',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='score',
        ),
    ]
